### ISSUE TITLE
Send message on PC windows - c#

### ISSUE THREAD

**Issue by autoprog** [fhstp/SoniTalk#5]
hi,
have code Encoder  text message, on PC windows , play audio and save audio wav, whith c#.
message PC ---> to device Android.

for test IOT.

thanks,

Carlos.

**Comment by aringot** [comment]
Hi, thanks for your interest, if I understand well you would like to send messages from a PC.

I think the easiest option would be to use the Android emulator with either the SoniTalk Demo App or your own app, using the SoniTalk SDK.

We did not implement the SoniTalk SDK in any other language than Java / Matlab (for the prototype), but can probably give you advice / answer questions if you need help porting it to C#.

Hope that helps.
